### ISSUE TITLE
[BUG] Webpage loading fails after run `azd up`, occasionally reloads successfully

### ISSUE THREAD

**Issue by Menghua1** [Azure-Samples/cosmos-db-nosql-dotnet-quickstart#49]
### Description

After run command `azd up`, click the endpoint to load web page, an error occurred, and in 5 reload results, 2 were successful and 3 had this error, as follows:
![image](https://github.com/user-attachments/assets/0136f183-945a-4f59-9c1b-7ef06d382eb9)

### Repro steps

1. Run `azd auth login`.
2. Run `azd init --template cosmos-db-nosql-dotnet-quickstart`.
3. Run `azd up`.
4. Click the web link.

### Expected behavior

After running `azd up`, the web page can be loaded successfully and **stably**.

### Environment
1. Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
2. OS: Windows
3. Templates: https://github.com/azure-samples/cosmos-db-nosql-dotnet-quickstart

@hemarina and @seesharprun for notification.

**Comment by seesharprun** [comment]
This is a transient bug I'm seeing with ACA related to websocket ports. I'm switching the deployment to App Service to see if that permanently resolves this port issue.

**Comment by seesharprun** [comment]
This has been fixed by setting up WebSocket polling

**Comment by Menghua1** [comment]
After testing the latest code, web page loading still fails, and occasionally reloading succeeds. The error page is as follows:
![image](https://github.com/user-attachments/assets/3951c4a0-229b-4abf-88fd-68a1cbd4086b)

**Comment by seesharprun** [comment]
There seems to be an issue with the HTTPS transport in Azure Container Apps.

- Related to #57

**Comment by seesharprun** [comment]
This should now be fixed.
