### ISSUE TITLE
[BUG] Fail to run this web application locally in the `src/web` folder

### ISSUE THREAD

**Issue by Menghua1** [Azure-Samples/cosmos-db-nosql-dotnet-quickstart#55]
### Description

Running the command `dotnet watch run` fails with the following error message. When the `.NET SDK` version is changed to 9.0, the command can succeed.
![image](https://github.com/user-attachments/assets/71ad2b84-fa5b-4fe6-b67e-f3729584d002)

### Repro steps

1. Run `azd auth login`.
2. Run `azd init --template cosmos-db-nosql-dotnet-quickstart`.
3. Run `azd up`.
4. Run `cd src/web`.
5. Run `dotnet watch run`.

### Expected behavior

Change the code to support `.NET SDK 8.0`, or change the .NET SDK in `Prerequisites` in Readme.md to `9.0`.

### Environment

- Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
- OS: Windows
- Templates: https://github.com/azure-samples/cosmos-db-nosql-dotnet-quickstart

@hemarina and @seesharprun for notification.

**Comment by seesharprun** [comment]
I'm updating the readme to specify .NET 9. .NET 9 is already used in the devcontainer configuration and CodeQL workflow.
