### ISSUE TITLE
[Optional] Publish to azure samples browser 

### ISSUE THREAD

**Issue by v-xuto** [Azure-Samples/cosmos-db-nosql-dotnet-quickstart#67]
### Description

This repository is added to [awesome-azd](https://aka.ms/awesome-azd) site and it is a Microsoft-authored template, we encourage you to [publish it to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main) if you are interested.

cc @hemarina

**Comment by v-xuto** [comment]
Metadata has been added to the Readme and is hidden. Close it.

**Comment by seesharprun** [comment]
https://learn.microsoft.com/en-us/samples/browse/?filter-products=cosmos&products=azure-cosmos-db&languages=azdeveloper&terms=Quickstart%20SDK
